### ISSUE TITLE
Do redirects support header links?

### ISSUE THREAD

**Issue by Andre601** [datarobot/mkdocs-redirects#20]
I was wondering, if the redirects created by this plugin do support header links.

For example:
Would a configuration that redirects `old_page.md` to `new_page.md` make https://example.com/old_page#header redirect to https://example.com/new_page#header?

From my basic testing does this not seem to be the case and I'm not sure if that is doable with redirects.

**Comment by Andre601** [comment]
Actually nevermind. There was a typo in my test and it now works. Sorry to bother.

**Comment by DominikaK** [comment]
While this has been reported as resolved, I am also encountering this issue at the moment, using `mkdocs-redirects==1.0.4`.

A redirect formulated as `'page_one.md': 'page_two.md#'` correctly redirects from `page_one.md` to `page_two.md`.
However, the following configuration is ignored:

``` yaml
nav:
    - 'Documentation': 'index.md'
    - 'Page one': 'page_one.md'
    - 'Page two': 'page_two.md'

plugins:
    - redirects:
        redirect_maps:
            'page_one.md#heading': 'page_two.md#heading'
```

When running `mkdocs serve`, the following error message is displayed:

```
WARNING  -  redirects plugin: 'page_one.md#heading' is not a valid markdown file!
WARNING  -  Redirect target 'page_two.md#heading' does not exist!
```
