### ISSUE TITLE
Allow to use regular expressions for redirects

### ISSUE THREAD

**Issue by djuarezg** [datarobot/mkdocs-redirects#29]
Right now it only allows a 1-1 correspondance. Sometimes when migrating documentation you may find yourself that externally referenced links may be broken.

If this plugin allows you to select regular expressions, it removes the need of any external redirection, such as one you could do by yourself with nginx.

**Comment by Andre601** [comment]
What I personally would like is support for wildcard patterns, to allow redirects of entire sections, similar to what Cloudflare allows in their redirect rules.

The common use-case is when you renamed an entire section from one name to another, resulting in X files having a new location. You would now need to set like X links, or make a redirect with the wildcard that would allow to change all pages with a single redirect.

Example-setup:
```yaml
plugins:
- redirects:
    redirect_maps:
      'old/*': 'new/$1' # The $1 would be the first wildcard in the path
```
The above would now allow `old/page1` to redirect to `new/page1`, `old/page2` redirect to `new/page2` and so on.

If such a feature is already available should it be mentioned in the readme.
