### ISSUE TITLE
Uppercase to Lowercase redirect result in weird loop

### ISSUE THREAD

**Issue by TRaSH-** [datarobot/mkdocs-redirects#43]
I'm trying to be more consistent with my Guide that runs on mkdocs

and i have a few pages i want to switch from upper case to lower case, but wanted for compatibility create redirects

```yaml
Sonarr/Sonarr-recommended-naming-scheme.md: Sonarr/sonarr-recommended-naming-scheme.md
Sonarr/Sonarr-Release-Profile-RegEx.md: Sonarr/sonarr-release-profile-regex.md
Sonarr/Sonarr-remote-path-mapping.md: Sonarr/sonarr-remote-path-mapping.md
 ```
 
 But when testing this on my local setup it looks like it loops or get's stuck
 
![image](https://user-images.githubusercontent.com/6155095/187300521-47821ccd-daa1-45b4-aae8-2505a8180a9a.png)
