### ISSUE TITLE
[Feature request] Use an external file to store redirections mapping

### ISSUE THREAD

**Issue by Guts** [datarobot/mkdocs-redirects#47]
Hello!

Sometimes, in large base documentation evolving for a few years, it's quite hard to maintain a healthy redirections mapping and it's not really convenient as it's stored within the `mkdocs.yml`.

Why not allowing to load redirections map from an external file, for example a CSV with an option (mutually exclusive with `redirect_maps`) like this:

```yaml
plugins:
    - redirects:
        redirect_file: "config/redirections.csv"
```
