### ISSUE TITLE
Use path based redirects

### ISSUE THREAD

**Issue by SteveRosam** [datarobot/mkdocs-redirects#54]
I would like to redirect from '/this-folder/' to '/another-folder/' or '/to-here/index.html'

**Comment by andgineer** [comment]
I think that related to https://github.com/mkdocs/mkdocs-redirects/issues/59

**Comment by pawamoy** [comment]
@SteveRosam do I understand correctly that you're looking for some wildcard feature, to redirect all files within `this-folder` to the files with same name in `another-folder`? Or all files within a folder to a single page? In that case I would close this as duplicate of #29.

If you're just trying to create 1:1 redirects, I believe you can do this:

```yaml
plugins:
- redirects:
    redirect_maps:
      this-folder.md: another-folder.md
```

To redirect to an existing HTML page, it's tracked in #18.
