### ISSUE TITLE
Does not with with i18n when using folder structure

### ISSUE THREAD

**Issue by nahuhh** [datarobot/mkdocs-redirects#63]
Related: https://github.com/mkdocs/mkdocs-redirects/issues/33
The related issue above is when using suffix.

This issue is to point out that folder structure is broken as well.

fails:
```
- plugins:
  - redirects:
      redirect_maps:
        'running-node/open-node-tor-onion.md': 'running-node/systemd.md'
```

it succeeds if i18n is disabled.
With folder structure, these files are located in folders like `en/running-node/open-node-tor-onion.md`

this plugin should respect 
`running-node/open-node-tor-onion.md` (same as the declaration in the nav) and/or perhaps accurately use relative redirects like 
```
 'running-node/open-node-tor-onion.md': '../running-node/systemd.md'
```
