### ISSUE TITLE
applying redirect maps from a file.

### ISSUE THREAD

**Issue by patrikwm** [datarobot/mkdocs-redirects#68]
Is it possible to read the redirect_map from a file? 

somehting similar to this.

```yaml
plugins:
  - redirects:
    redirect_map_file: my_redirects.yml
```

and then the `my_redirects.yml` file will contain.

```yaml
redirect_maps:
  "my_old_url.md": "cool_page/my_new_url.md"
  "my_old_url2.md": "cool_page/my_new_url2.md"
  "my_old_url3.md": "cool_page/my_new_url3.md"
```

This would help when there are a lot of old urls that are removed or should be pointing at something new. Else the mkdocs.yml will be really big.
