### ISSUE TITLE
Feature request: Heading-based redirects.

### ISSUE THREAD

**Issue by rudolfbyker** [datarobot/mkdocs-redirects#69]
I use a custom scraper that runs in my CI to detect when I break any URLs that might exist in search engines, or that have been shared by users. Then I use `mkdocs-redirects` to fix those links before deploying the next version of my docs. This works well, until I have to split a page into two separate pages.

Since we're doing client-side redirects anyway, could we support heading-based redirects? Heading-based redirects are not possible in the context of SSR, because the anchor (the `#foo` part of the URL) is not sent to the server. But the browser knows what it is, so with a little bit of JS, we can easily detect which heading is desired, and redirect based on that.

Currently, the following script is generated:

```js
var anchor=window.location.hash.substr(1);
location.href="destination.html"+(anchor?"#"+anchor:"")
```

This could easily be expanded with a simple `switch` statement:

```js
var anchor=window.location.hash.substr(1);
switch (anchor) {
  case 'heading1':
    location.href="page1.html"
    break;
  case 'heading2':
    location.href="page2.html"
    break;
  default:
    location.href="page3.html"
}
```

The `mkdocs.yaml` config could look something like this:

```yaml
plugins:
  - redirects:
      redirect_maps:
        "original.md#heading1": page1.md
        "original.md#heading2": page2.md
        "original.md": page3.md
```

or, if you don't like the flat structure:

```yaml
plugins:
  - redirects:
      redirect_maps:
        "original.md":
          "#heading1": page1.md
          "#heading2": page2.md
          "default": page3.md
```

or, if you want to keep the door open for other types of redirects (which I can't conceive of now):

```yaml
plugins:
  - redirects:
      redirect_maps:
        "original.md":
          "anchors":
            "heading1": page1.md
            "heading2": page2.md
          "default": page3.md
```

**Comment by pawamoy** [comment]
Thanks for the request @rudolfbyker. That would be a nice addition, similar to #64.

I worry that users will expect such redirections to work in *existing* pages. But the plugin would have to modify the existing page to add the relevant ~~headings and~~ JS code, which is not trivial. This could definitely be documented as a limitation though.

The flat structure would mean the plugin must now iterate on all redirections in a first step, to reconcile page redirects and page+heading redirects.

**Comment by rudolfbyker** [comment]
Sounds more complicated to implement than I anticipated.

**Comment by pawamoy** [comment]
Sorry, not sure what I was thinking, but surely the plugin wouldn't have to add any heading, just JS code, to redirect depending on the anchor in the URL. So, a bit less complicated :)

**Comment by wwarriner** [comment]
I took a look at implementing this, roughly, and here are a couple thoughts blocking me. I'm not sure the best way to proceed. I am going to use the term "anchor" to refer to the part of the URL beginning with a `#` symbol.

1. Yes, JS can be used to redirect from old anchors to new pages. This would be accomplished by adding something like a JS object to serve as a "dict" with hard-coded sources and destinations. The JS code would select the destination based on the supplied anchor. The python side would need to write the JS code into the HTML template. This isn't impossible, but has some intricacies that may require some re-writing of the plugin.

1. If anchors in the old page can lead to more than one new page, how do we indicate which is the canonical URL for the redirect? The HTML_TEMPLATE in the code has a `<link rel="canonical" a=$url>` tag. Right now, that `$url` is the URL of the redirect target. I have not found any advice in Google searches. I don't think this is a common-enough issue in most web applications to have any experts weighing in. Happy to be proven wrong!

1. How do we handle the case where we want the old page to continue existing, and only specific anchors should be redirected? I'm sure this can be handled with redirects, but it means we need to add JS content to an existing page. The plugin does not have machinery for this right now.

Related: https://github.com/squidfunk/mkdocs-material/discussions/3764

**Comment by pawamoy** [comment]
> If anchors in the old page can lead to more than one new page, how do we indicate which is the canonical URL for the redirect?

- Page exists: no canonical URL (no `link` tag). The page is not a redirect so shouldn't be labeled as such.
- Page does not exist:
  - Heading redirects only: use URL of first redirect. Alternatively, use page that is most redirected to.
  - Heading redirects and global/page redirect: use the page redirect

For example:

```yaml
plugins:
  - redirects:
      redirect_maps:
        "old.md#heading1": page1.md
        "old.md#heading2": page2.md
        "old.md": page3.md
```

--> use page3

---

```yaml
plugins:
  - redirects:
      redirect_maps:
        "old.md#heading1": page1.md
        "old.md#heading2": page2.md
```

--> use page1

---

```yaml
plugins:
  - redirects:
      redirect_maps:
        "existing.md#heading1": page1.md
        "existing.md#heading2": page2.md
```

--> no link tag

**Comment by wwarriner** [comment]
Thanks for your thoughts! I think that the first and third cases are sensible. The second case ("use page1") would make the plugin opinionated.

This could be dealt with via some interface and options for how to select which page would serve as the canonical redirect, but that might complicate the user experience and the code unnecessarily. I'm interested to give this a try again, maybe later this week or next I'll give it a go.

Brainstorming options that spring to mind for case 2 (I'm ignoring how to implement selection, for now):

- No canonical
- First appearing
- Last appearing
- Most-frequently appearing
- Manual selection

**Comment by pawamoy** [comment]
An interesting feature of "first" or "last" is that it allows manual selection thanks to ordering 🙂

**Comment by rudolfbyker** [comment]
> How do we handle the case where we want the old page to continue existing, and only specific anchors should be redirected?

`mkdocs.yaml`

```yaml
plugins:
  - redirects:
      redirect_maps:
        "original.md#heading-1": "page1.md"  # This heading was moved to a new page.
        "original.md#heading-2": "page2.md#new-heading-2"  # This heading was moved to an existing page.
        # "original.md" continues to exist.
```

In the `<head>` of the original page:

```js
var anchor=window.location.hash.substr(1);
switch (anchor) {
  case 'heading-1':
    location.href="page1.html"
    break;
  case 'heading-2':
    location.href="page2.html#new-heading-2"
    break;
  default:
    // Stay here.
}
```

Thanks for considering this :)
